# FROM node:20-alpine

# WORKDIR /app

# COPY package*.json ./
# RUN npm ci

# COPY . .
# RUN npm run build

# ENV NODE_ENV=production
# ENV PORT=8080

# EXPOSE 8080

# CMD ["npm", "start"]


# syntax=docker/dockerfile:1

##########  Base  ##########
# Node 22 on Alpine keeps the image small. Next.js standalone on Alpine
# needs libc6-compat, so we add it here.
FROM node:22-alpine AS base
RUN apk add --no-cache libc6-compat
WORKDIR /app

##########  Dependencies  ##########
FROM base AS deps
# Copy manifests first so this layer stays cached unless dependencies change.
COPY package.json package-lock.json ./
RUN npm ci

##########  Builder  ##########
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# NEXT_PUBLIC_* variables are inlined into the browser bundle at BUILD time.
# Pass this as a --build-arg if the app uses it client-side; a runtime secret
# alone will NOT reach already-built client code.
ARG NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL

ENV NEXT_TELEMETRY_DISABLED=1
# Requires `output: "standalone"` in next.config.ts (see the note in chat).
RUN npm run build

##########  Runner  ##########
FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Bind to all interfaces — required for Cloud Run / Docker to reach the server.
ENV HOSTNAME=0.0.0.0
# Cloud Run overrides PORT at runtime; 3000 is just the local default.
ENV PORT=3000

# Don't run as root.
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Standalone output = a minimal server.js plus only the node_modules it traced.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# Static assets and /public are NOT part of standalone — copy them in explicitly.
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs
EXPOSE 3000

# server.js is generated by Next's standalone output.
CMD ["node", "server.js"]
